version: '3.7'

services:
  app:
    container_name: workery-front
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - '1337:80'

# Usage:
#   docker-compose -f prod.docker-compose.yml up
#
# Go to in your browser:
#   http://localhost:1337/
